
import scrapy

class IssuerItem(scrapy.Item):
    issuer_code = scrapy.Field()
    company_name_ch = scrapy.Field()
    company_name_en = scrapy.Field()
    short_name_ch = scrapy.Field()
    short_name_en = scrapy.Field()
    exchange = scrapy.Field()
    board = scrapy.Field()
    region = scrapy.Field()
    status = scrapy.Field()
    org_type = scrapy.Field()
    evidence_url = scrapy.Field()
    snapshot_date = scrapy.Field()

class SecurityItem(scrapy.Item):
    issuer_code = scrapy.Field()
    stock_code = scrapy.Field()
    exchange = scrapy.Field()
    board = scrapy.Field()
    share_class = scrapy.Field()
    status = scrapy.Field()
    list_date = scrapy.Field()
    delist_date = scrapy.Field()
    isin = scrapy.Field()
    evidence_url = scrapy.Field()
    snapshot_date = scrapy.Field()

class CompanyDetailItem(scrapy.Item):
    issuer_code = scrapy.Field()
    company_name_ch = scrapy.Field()
    company_name_en = scrapy.Field()
    business_profile_cn = scrapy.Field()
    business_scope_cn = scrapy.Field()
    industry_csic = scrapy.Field()
    registered_capital = scrapy.Field()
    legal_representative = scrapy.Field()
    established_date = scrapy.Field()
    registered_address = scrapy.Field()
    website = scrapy.Field()
    email = scrapy.Field()
    phone = scrapy.Field()
    disclosure_lang = scrapy.Field()
    evidence_url = scrapy.Field()
    snapshot_date = scrapy.Field()

class TopShareholderItem(scrapy.Item):
    issuer_code = scrapy.Field()
    report_date = scrapy.Field()
    rank = scrapy.Field()
    shareholder_name_ch = scrapy.Field()
    shareholder_name_en = scrapy.Field()
    holder_type = scrapy.Field()
    shares_held = scrapy.Field()
    holding_ratio = scrapy.Field()
    share_class = scrapy.Field()
    restricted_flag = scrapy.Field()
    change_direction = scrapy.Field()
    evidence_url = scrapy.Field()
    snapshot_date = scrapy.Field()

class JoinedCompanySecurityItem(scrapy.Item):
    issuer_code = scrapy.Field()
    company_name_ch = scrapy.Field()
    company_name_en = scrapy.Field()
    stock_code = scrapy.Field()
    exchange = scrapy.Field()
    board = scrapy.Field()
    share_class = scrapy.Field()
    status = scrapy.Field()
    list_date = scrapy.Field()
    delist_date = scrapy.Field()
    isin = scrapy.Field()
    issuer_evidence_url = scrapy.Field()
    security_evidence_url = scrapy.Field()
    snapshot_date = scrapy.Field()
